## Load the dataset

In [16]:
# Reading the data
import pandas as pd
import numpy as np
import csv
import scipy.io as sio
import matplotlib.pyplot as plt
from scipy import stats
import re
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline

train_data = pd.read_csv('../Datasets/preprocessed_dataset.csv', index_col=0 )


In [17]:
train_data.head()

Breed            Breed2  MixedBreed  isCat  Color  \
0   shetland sheepdog               NaN        True      0  Brown   
1  domestic shorthair               NaN        True      1  Cream   
2            pit bull               NaN        True      0   Blue   
3  domestic shorthair               NaN        True      1   Blue   
4          lhasa apso  miniature poodle       False      0    Tan   

  ColorPattern Color2 ColorPattern2  AgeuponOutcome      OutcomeType  \
0          NaN  White           NaN           365.0  Return_to_owner   
1        Tabby    NaN           NaN           365.0       Euthanasia   
2          NaN  White           NaN           730.0         Adoption   
3        Cream    NaN           NaN            21.0         Transfer   
4          NaN    NaN           NaN           730.0         Transfer   

  SexuponOutcome   Name  
0  Neutered Male   True  
1  Spayed Female   True  
2  Neutered Male   True  
3    Intact Male  False  
4  Neutered Male  False

In [18]:
values = pd.concat([train_data['Breed'], train_data['Breed2'].fillna('')]).unique()

#breedValues = (train_data[['Breed','Breed2']].fillna(''))

le = LabelEncoder()
le.fit(values)
breed1 = label_encoder.transform(train_data['Breed'].fillna(''))
breed1 = breed1.reshape(len(breed1), 1)
breed2 = le.transform(train_data['Breed2'].fillna(''))
breed2 = breed2.reshape(len(breed2), 1)

nummericBreeds = np.append(breed1,breed2, axis=1) #length of 26729
nummericBreedsUniques = np.unique(nummericBreeds) # Length of 224

onehot_encoder = OneHotEncoder(sparse=False)
#onehot_encoder = OneHotEncoder(categories=[nummericBreedsUniques]*len(nummericBreeds), sparse=False)
onehot_encoded =  onehot_encoder.fit_transform(nummericBreeds)
print(onehot_encoder.categories_)

NameError: name 'label_encoder' is not defined

In [19]:
x = np.array([[3, 5, 1]])
_, n_features = np.shape(x)
n = 8
print(x)
ohe = OneHotEncoder(categories=[range(n)]*n_features, sparse=False)
o = ohe.fit_transform(x)
o = o.reshape(1, 3, 8)
print(o)

[[3 5 1]]
[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [20]:
#encoded = pd.DataFrame(onehot_encoder.fit_transform(train_data[['Breed', 'Breed2']].fillna('')), onehot_encoder=onehot_encoder.get_feature_names(['Breed', 'Breed2']))

#encoded = onehot_encoder.fit_transform(pd.DataFrame(onehot_encoder.fit_transform(train_data[['Breed', 'Breed2']]), columns=onehot_encoder.get_feature_names(['Breed', 'Breed2'])))
train_data.head()

Breed            Breed2  MixedBreed  isCat  Color  \
0   shetland sheepdog               NaN        True      0  Brown   
1  domestic shorthair               NaN        True      1  Cream   
2            pit bull               NaN        True      0   Blue   
3  domestic shorthair               NaN        True      1   Blue   
4          lhasa apso  miniature poodle       False      0    Tan   

  ColorPattern Color2 ColorPattern2  AgeuponOutcome      OutcomeType  \
0          NaN  White           NaN           365.0  Return_to_owner   
1        Tabby    NaN           NaN           365.0       Euthanasia   
2          NaN  White           NaN           730.0         Adoption   
3        Cream    NaN           NaN            21.0         Transfer   
4          NaN    NaN           NaN           730.0         Transfer   

  SexuponOutcome   Name  
0  Neutered Male   True  
1  Spayed Female   True  
2  Neutered Male   True  
3    Intact Male  False  
4  Neutered Male  False

In [21]:

enc = LabelEncoder()
enc_train_data = pd.DataFrame() 
enc_train_data['Breed'] = enc.fit_transform(train_data['Breed'].fillna(''))
enc_train_data['Breed2'] = enc.fit_transform(train_data['Breed2'].fillna(''))
#enc_train_data['MixedBreed'] = enc.fit_transform(train_data['MixedBreed'].fillna(''))
enc_train_data['Color'] = enc.fit_transform(train_data['Color'].fillna(''))
enc_train_data['ColorPattern'] = enc.fit_transform(train_data['ColorPattern'].fillna(''))
enc_train_data['Color2'] = enc.fit_transform(train_data['Color2'].fillna(''))
enc_train_data['ColorPattern2'] = enc.fit_transform(train_data['ColorPattern2'].fillna(''))
#enc_train_data['OutcomeType'] = enc.fit_transform(train_data['OutcomeType'].fillna(''))
enc_train_data['SexuponOutcome'] = enc.fit_transform(train_data['SexuponOutcome'].fillna(''))
#enc_train_data['Name'] = enc.fit_transform(train_data['Name'].fillna(''))
#enc_train_data['AgeuponOutcome'] = enc.fit_transform(train_data['AgeuponOutcome'])

train_data.head()

Breed            Breed2  MixedBreed  isCat  Color  \
0   shetland sheepdog               NaN        True      0  Brown   
1  domestic shorthair               NaN        True      1  Cream   
2            pit bull               NaN        True      0   Blue   
3  domestic shorthair               NaN        True      1   Blue   
4          lhasa apso  miniature poodle       False      0    Tan   

  ColorPattern Color2 ColorPattern2  AgeuponOutcome      OutcomeType  \
0          NaN  White           NaN           365.0  Return_to_owner   
1        Tabby    NaN           NaN           365.0       Euthanasia   
2          NaN  White           NaN           730.0         Adoption   
3        Cream    NaN           NaN            21.0         Transfer   
4          NaN    NaN           NaN           730.0         Transfer   

  SexuponOutcome   Name  
0  Neutered Male   True  
1  Spayed Female   True  
2  Neutered Male   True  
3    Intact Male  False  
4  Neutered Male  False

In [22]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded =  onehot_encoder.fit_transform(enc_train_data)
print(enc_train_data.shape)
print(onehot_encoded.shape)
print(onehot_encoded)

(26729, 7)
(26729, 440)
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


C:\Users\Sjoerd\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [23]:
encodedDataframe = pd.DataFrame(onehot_encoded)
encodedDataframe['MixedBreed'] = train_data['MixedBreed']
encodedDataframe['Name'] = train_data['Name']
encodedDataframe = encodedDataframe.astype(int)

encodedDataframe['AgeuponOutcome'] = train_data['AgeuponOutcome'].fillna(-1)
encodedDataframe['OutcomeType'] = enc.fit_transform(train_data['OutcomeType'].fillna(''))
encodedDataframe['OutcomeTypeString'] = train_data['OutcomeType'].fillna('')


In [26]:
encodedDataframe.to_csv('../Datasets/oneHotEncoded_dataset.csv')


In [25]:
encodedDataframe.head()

0  1  2  3  4  5  6  7  8  9        ...          435  436  437  438  439  \
0  0  0  0  0  0  0  0  0  0  0        ...            0    0    1    0    0   
1  0  0  0  0  0  0  0  0  0  0        ...            0    0    0    1    0   
2  0  0  0  0  0  0  0  0  0  0        ...            0    0    1    0    0   
3  0  0  0  0  0  0  0  0  0  0        ...            0    1    0    0    0   
4  0  0  0  0  0  0  0  0  0  0        ...            0    0    1    0    0   

   MixedBreed  Name  AgeuponOutcome  OutcomeType  OutcomeTypeString  
0           1     1           365.0            3    Return_to_owner  
1           1     1           365.0            2         Euthanasia  
2           1     1           730.0            0           Adoption  
3           1     0            21.0            4           Transfer  
4           0     0           730.0            4           Transfer  

[5 rows x 445 columns]

In [85]:
encodedDataframe.isnull().sum()

0                  0
1                  0
2                  0
3                  0
4                  0
5                  0
6                  0
7                  0
8                  0
9                  0
10                 0
11                 0
12                 0
13                 0
14                 0
15                 0
16                 0
17                 0
18                 0
19                 0
20                 0
21                 0
22                 0
23                 0
24                 0
25                 0
26                 0
27                 0
28                 0
29                 0
                  ..
414                0
415                0
416                0
417                0
418                0
419                0
420                0
421                0
422                0
423                0
424                0
425                0
426                0
427                0
428                0
429                0
430          